server:
  port: 8080
  servlet:
    session:
      cookie:
        name: SOHOID

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/start_soho
    username: ${JDBC_UNAME}
    password: ${JDBC_PASSWD}

mybatis:
  mapper-locations: classpath:/META-INFO/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true